"""Mock objects for testing"""
#pylint: disable=line-too-long

PERMIT_TYPES = ["existingBuilding", "newConstruction", "existingPermitApplication"]

SINGLE_ROW = [
    "5f19eb423339194c18c45c7a",
    "",
    "",
    "",
    "2020-07-23T19:55:46.744Z",
    "2020-07-23T19:55:46.745Z",
    "existingBuilding",
    "yes",
    "yes",
    "contractor",
    "",
    "",
    "",
    "",
    "",
    "",
    "San Francisco",
    "california",
    "94124",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "123456",
    "existingProjectAddress1",
    "existingProjectAddress2",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "SAN FRANCISCO",
    "california",
    "94133",
    "FALSE",
    "FALSE",
    "FALSE",
    "FALSE",
    "FALSE",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "newBuildingLocation",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "existingBuildingAddress1",
    "existingBuildingAddress2",
    "San Francisco",
    "california",
    "94109",
    "0622",
    "003",
    "vAProtectedWoodFrame",
    "48",
    "5",
    "0",
    "mixedUse",
    "r2ResidentialApartmentCondominiums,\nmMercantile",
    "no",
    "no",
    "37000",
    "DO STUFF",
    "vAProtectedWoodFrame",
    "48",
    "5",
    "0",
    "mixedUse",
    "r2ResidentialApartmentCondominiums,\nmMercantile",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "no",
    "no",
    "no",
    "no",
    "no",
    "",
    "no",
    "",
    "no",
    "no",
    "no",
    "no",
    "",
    "",
    "",
    "",
    "",
    "",
    "no",
    "no",
    "no",
    "",
    "",
    "[{\"storage\": \"s3\", \"name\": \"A.pdf\", \"bucket\": \"bucket1\", \"key\": \"A.pdf\", \"url\": \"https://bucket1.amazonaws.com/A.pdf\", \"acl\": \"private\", \"size\": 1, \"type\": \"application/pdf\", \"originalName\": \"A.pdf\"}, {\"storage\": \"s3\", \"name\": \"B.pdf\", \"bucket\": \"bucket1\", \"key\": \"B.pdf\", \"url\": \"https://bucket1.s3.amazonaws.com/B.pdf\", \"acl\": \"private\", \"size\": 1, \"type\": \"application/pdf\", \"originalName\": \"B.pdf\"}]",
    "[{\"storage\": \"s3\", \"name\": \"C.pdf\", \"bucket\": \"bucket1\", \"key\": \"C.pdf\", \"url\": \"https://bucket1.amazonaws.com/C.pdf\", \"acl\": \"private\", \"size\": 1, \"type\": \"application/pdf\", \"originalName\": \"C.pdf\"}, {\"storage\": \"s3\", \"name\": \"D.pdf\", \"bucket\": \"bucket1\", \"key\": \"D.pdf\", \"url\": \"https://bucket1.s3.amazonaws.com/D.pdf\", \"acl\": \"private\", \"size\": 1, \"type\": \"application/pdf\", \"originalName\": \"D.pdf\"}]",
    "FALSE",
    "",
    "Have_workers_comp_insurance",
    "TRUE",
    "2020-07-23T19:49:37.000Z",
    "existingBuildingAddress1",
    "existingBuildingAddress2",
    "https://bucket1.amazonaws.com/A.pdf,\nhttps://bucket1.s3.amazonaws.com/B.pdf,\nhttps://bucket1.amazonaws.com/C.pdf,\nhttps://bucket1.s3.amazonaws.com/D.pdf",
    "[]",
    "TRUE",
    "FALSE"
]

JSON_OBJ = {
    "_id":"5f19eb423339194c18c45c7a",
    "data":{
        "actionState":"",
        "bluebeamStatus":"",
        "ptsStatus":"",
        "permitType":"existingBuilding",
        "reviewOverTheCounter":"yes",
        "onlyFireDepartmentReview":"yes",
        "applicantType":"contractor",
        "applicantFirstName":"",
        "applicantLastName":"",
        "applicantPhoneNumber":"",
        "applicantEmail":"",
        "applicantAddress1":"",
        "applicantAddress2":"",
        "applicantCity":"San Francisco",
        "Page2State":"california",
        "applicantZipCode":"94124",
        "applicantContractorLicenseNumber":"",
        "applicantContractorLicenseExpirationDate":"",
        "applicantBTRC":"",
        "applicantArchitectLicenseNumber":"",
        "applicantArchitectLicenseExpirationDate":"",
        "applicantEngineerLicenseNumber":"",
        "applicantEngineerLicenseExpirationDate":"",
        "buildingPermitApplicationNumber":"123456",
        "existingProjectAddress1":"existingProjectAddress1",
        "existingProjectAddress2":"existingProjectAddress2",
        "existingProjectZipCode":"",
        "existingProjectDescribeApplicationChanges":"",
        "ownerName":"",
        "ownerPhoneNumber":"",
        "ownerEmail":"",
        "ownerAddress1":"",
        "ownerAddress2":"",
        "ownerCity":"SAN FRANCISCO",
        "ownerState":"california",
        "ownerZipCode":"94133",
        "teamMembers":{
            "agent":"FALSE",
            "architect":"FALSE",
            "attorneyInFact":"FALSE",
            "contractor":"FALSE",
            "engineer":"FALSE"
        },
        "agentOrganizationName":"",
        "agentName":"",
        "agentEmail":"",
        "architectOrganizationName":"",
        "architectName":"",
        "architectEmail":"",
        "architectLicenseNumber":"",
        "architectLicenseExpirationDate":"",
        "attorneyOrganizationName":"",
        "attorneyName":"",
        "attorneyEmail":"",
        "contractorOrganizationName":"",
        "contractorName":"",
        "contractorEmail":"",
        "contractorLicenseNumber":"",
        "contractorLicenseExpirationDate":"",
        "contractorBTRC":"",
        "engineerOrganizationName":"",
        "engineerName":"",
        "engineerEmail":"",
        "engineerLicenseNumber":"",
        "engineerLicenseExpirationDate":"",
        "newBuildingLocation":"newBuildingLocation",
        "newBuildingBlockNumber":"",
        "newBuildingLotNumber":[
            ""
        ],
        "newBuildingLotFront":"",
        "newBuildingLotBack":"",
        "newBuildingLotAverageDepth":"",
        "newBuildingStreetFaced":"",
        "newBuildingStreetSide":"",
        "newBuildingNearestCrossStreet":"",
        "newBuildingCrossStreetDirection":"",
        "newBuildingCrossStreetDistance":"",
        "newBuildingLotHasOtherBuilding":"",
        "existingBuildingAddress1":"existingBuildingAddress1",
        "existingBuildingAddress2":"existingBuildingAddress2",
        "existingBuildingCity":"San Francisco",
        "existingBuildingState":"california",
        "existingBuildingZipCode":"94109",
        "existingBuildingBlockNumber":"0622",
        "existingBuildingLotNumber":[
            "003"
        ],
        "existingBuildingConstructionType":"vAProtectedWoodFrame",
        "existingBuildingDwellingUnits":"48",
        "existingBuildingOccupancyStories":"5",
        "existingBuildingBasementsAndCellars":"0",
        "existingBuildingPresentUse":"mixedUse",
        "existingBuildingOccupancyClass":[
            "r2ResidentialApartmentCondominiums",
            "mMercantile"
        ],
        "sitePermitForm38":"no",
        "noticeOfViolation":"no",
        "estimatedCostOfProject":"37000",
        "projectDescription":"DO STUFF",
        "typeOfConstruction":"vAProtectedWoodFrame",
        "proposedDwellingUnits":"48",
        "proposedOccupancyStories":"5",
        "proposedBasementsAndCellars":"0",
        "proposedUse":"mixedUse",
        "occupancyClass":[
            "r2ResidentialApartmentCondominiums",
            "mMercantile"
        ],
        "constructionLenderName":"",
        "constructionLenderBranchDesignation":"",
        "constructionLenderAddress1":"",
        "constructionLenderAddress2":"",
        "constructionLenderCity":"",
        "constructionLenderState":"",
        "constructionLenderZipCode":"",
        "sitePermitForm12":"",
        "newEstimatedCostOfProject":"",
        "newProjectDescription":"",
        "newTypeOfConstruction":"",
        "newBuildingUse":"",
        "newOccupancyClass":"",
        "newGroundFloorArea":"",
        "newBuildingFrontHeight":"",
        "newDwellingUnits":"",
        "newOccupancyStories":"",
        "newBasements":"",
        "newConstructionLenderName":"",
        "newConstructionLenderBranchDesignation":"",
        "constructionLenderAddress3":"",
        "constructionLenderAddress4":"",
        "constructionLenderCity1":"",
        "constructionLenderState1":"",
        "constructionLenderZipCode1":"",
        "alterOrConstructDriveway":"no",
        "useStreetSpace":"no",
        "electricalWork":"no",
        "plumbingWork":"no",
        "additionalHeightOrStory":"no",
        "newCenterLineFrontHeight":"",
        "deckOrHorizontalExtension":"no",
        "groundFloorArea":"",
        "repairOrAlterSidewalk":"no",
        "extendBeyondPropertyLine":"no",
        "otherExistingBuildings":"no",
        "changeOfOccupancy":"no",
        "alterOrConstructDrivewayNew":"",
        "extendBeyondPropertyLineNew":"",
        "useStreetSpaceNew":"",
        "additionalStoriesNew":"",
        "howManyAdditionalStoriesNew":"",
        "useSidewalkSpaceNew":"",
        "affordableHousing":"no",
        "developmentAgreement":"no",
        "accessoryDwellingUnit":"no",
        "uploadType":"",
        "bluebeamId":"",
        "optionalUploads":[
            {
                "storage": "s3",
                "name": "A.pdf",
                "bucket": "bucket1",
                "key": "A.pdf",
                "url": "https://bucket1.amazonaws.com/A.pdf",
                "acl": "private",
                "size": 1,
                "type": "application/pdf",
                "originalName": "A.pdf"
            },
            {
                "storage": "s3",
                "name": "B.pdf",
                "bucket": "bucket1",
                "key": "B.pdf",
                "url": "https://bucket1.s3.amazonaws.com/B.pdf",
                "acl": "private",
                "size": 1,
                "type": "application/pdf",
                "originalName": "B.pdf"
            }
        ],
        "requiredUploads":[
            {
                "storage": "s3",
                "name": "C.pdf",
                "bucket": "bucket1",
                "key": "C.pdf",
                "url": "https://bucket1.amazonaws.com/C.pdf",
                "acl": "private",
                "size": 1,
                "type": "application/pdf",
                "originalName": "C.pdf"
            },
            {
                "storage": "s3",
                "name": "D.pdf",
                "bucket": "bucket1",
                "key": "D.pdf",
                "url": "https://bucket1.s3.amazonaws.com/D.pdf",
                "acl": "private",
                "size": 1,
                "type": "application/pdf",
                "originalName": "D.pdf"
            }
        ],
        "noPlansPermit":"FALSE",
        "notes":"",
        "workersCompRadio":"Have_workers_comp_insurance",
        "iHerebyCertifyCheckBox":"TRUE",
        "dateTime":"2020-07-23T19:49:37.000Z",
        "projectLocation1":"existingBuildingAddress1",
        "projectLocation2":"existingBuildingAddress2",
        "fileLinks":[
            "https://bucket1.amazonaws.com/A.pdf",
            "https://bucket1.s3.amazonaws.com/B.pdf",
            "https://bucket1.amazonaws.com/C.pdf",
            "https://bucket1.s3.amazonaws.com/D.pdf"
        ],
        "confirmationUploads":[],
        "priorityProjectSelections":{
            "isInDevelopmentAgreement":"TRUE",
            "is100AffordableHousing":"FALSE"
        }
    },
    "created":"2020-07-23T19:55:46.744Z",
    "modified":"2020-07-23T19:55:46.745Z"
}

PATCH_RESPONSE = {
    "status": "success",
    "data": {
        "updates": [
            {
                "range": "B15",
                "values": [
                    [
                        "Queued for Bluebeam"
                    ]
                ]
            }
        ]
    }
}
