"""Mock objects for testing"""
#pylint: disable=line-too-long

PERMIT_TYPES = ["existingBuilding", "newConstruction", "existingPermitApplication"]

SINGLE_ROW = [
    "5f19eb423339194c18c45c7a",
    "",
    "",
    "",
    "2020-07-23T19:55:46.744Z",
    "2020-07-23T19:55:46.745Z",
    "existingBuilding",
    "yes",
    "yes",
    "contractor",
    "",
    "",
    "",
    "",
    "",
    "",
    "San Francisco",
    "california",
    "94124",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "123456",
    "existingProjectAddress1",
    "existingProjectAddress2",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "SAN FRANCISCO",
    "california",
    "94133",
    "FALSE",
    "FALSE",
    "FALSE",
    "FALSE",
    "FALSE",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "newBuildingLocation",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "existingBuildingAddress1",
    "existingBuildingAddress2",
    "San Francisco",
    "california",
    "94109",
    "0622",
    "003",
    "vAProtectedWoodFrame",
    "48",
    "5",
    "0",
    "",
    "r2ResidentialApartmentCondominiums,\nmMercantile",
    "no",
    "no",
    "37000",
    "DO STUFF",
    "vAProtectedWoodFrame",
    "48",
    "5",
    "0",
    "",
    "r2ResidentialApartmentCondominiums,\nmMercantile",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "no",
    "no",
    "no",
    "no",
    "no",
    "",
    "no",
    "",
    "no",
    "no",
    "no",
    "no",
    "",
    "",
    "",
    "",
    "",
    "",
    "no",
    "no",
    "no",
    "",
    "",
    "[{\"storage\": \"s3\", \"name\": \"A.pdf\", \"bucket\": \"bucket1\", \"key\": \"A.pdf\", \"url\": \"https://bucket1.amazonaws.com/A.pdf\", \"acl\": \"private\", \"size\": 1, \"type\": \"application/pdf\", \"originalName\": \"A.pdf\"}, {\"storage\": \"s3\", \"name\": \"B.pdf\", \"bucket\": \"bucket1\", \"key\": \"B.pdf\", \"url\": \"https://bucket1.s3.amazonaws.com/B.pdf\", \"acl\": \"private\", \"size\": 1, \"type\": \"application/pdf\", \"originalName\": \"B.pdf\"}]",
    "[{\"storage\": \"s3\", \"name\": \"C.pdf\", \"bucket\": \"bucket1\", \"key\": \"C.pdf\", \"url\": \"https://bucket1.amazonaws.com/C.pdf\", \"acl\": \"private\", \"size\": 1, \"type\": \"application/pdf\", \"originalName\": \"C.pdf\"}, {\"storage\": \"s3\", \"name\": \"D.pdf\", \"bucket\": \"bucket1\", \"key\": \"D.pdf\", \"url\": \"https://bucket1.s3.amazonaws.com/D.pdf\", \"acl\": \"private\", \"size\": 1, \"type\": \"application/pdf\", \"originalName\": \"D.pdf\"}]",
    "FALSE",
    "",
    "Have_workers_comp_insurance",
    "TRUE",
    "2020-07-23T19:49:37.000Z",
    "existingBuildingAddress1",
    "",
    "https://bucket1.amazonaws.com/A.pdf,\nhttps://bucket1.s3.amazonaws.com/B.pdf,\nhttps://bucket1.amazonaws.com/C.pdf,\nhttps://bucket1.s3.amazonaws.com/D.pdf",
    "[]",
    "TRUE",
    "FALSE",
    "23",
    "",
    "streetName",
    "",
    "",
    "21",
    "100",
    "11111",
    "FALSE",
    "FALSE",
    "FALSE",
    "FALSE",
    "FALSE",
    "a,\nb",
    "FALSE",
    "FALSE",
    "FALSE",
    "FALSE",
    "FALSE",
    "a,\nb",
    "FALSE",
    "FALSE",
    "FALSE",
    "FALSE",
    "FALSE",
    "a,\nb",
    'applicant org',
    'owner org',
    'owner first',
    'owner last',
    'agent first',
    'agent last',
    '4151111111',
    'agent addr 1',
    'agent addr 2',
    'agent city',
    'agent state',
    '11111',
    'architect first',
    'architect last',
    '4152222222',
    'architect addr 1',
    'architect addr 2',
    'architect city',
    'architect state',
    '11111',
    'attorney first',
    'attorney last',
    '4153333333',
    'attorney addr 1',
    'attorney addr 2',
    'attorney city',
    'attorney state',
    '11111',
    'contractor first',
    'contractor last',
    '4154444444',
    'contractor addr 1',
    'contractor addr 2',
    'contractor city',
    'contractor state',
    '11111',
    'eng first',
    'eng last',
    '4155555555',
    'engineer addr 1',
    'engineer addr 2',
    'engineer city',
    'engineer state',
    '11111'
]

SINGLE_ROW_ADDENDA = [
    "5ed81beb463bc6df71e2500f",
    "",
    "",
    "2020-06-03 02:53 PM PDT",
    "2020-06-03 02:53 PM PDT",
    "agent",
    "Test",
    "Agent",
    "(415) 111-1111",
    "test@test.test",
    "123 Test Street",
    "",
    "San Francisco",
    "california",
    "94111",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "12345678",
    "123 Main Street",
    "",
    "94100",
    "yes",
    "yes",
    "yes",
    "TRUE",
    "TRUE",
    "FALSE",
    "FALSE",
    "FALSE",
    "FALSE",
    "FALSE",
    "",
    "12,345,678",
    "2",
    "0",
    "[{\"storage\": \"s3\", \"name\": \"fake_file-9331c51c-70c8-4548-a3cd-ffb154ef5b35.pdf\", \"bucket\": \"bucketeer-5537c4b2-1591-443b-97e3-be39fb46da74\", \"key\": \"formio-live/fake_file-9331c51c-70c8-4548-a3cd-ffb154ef5b35.pdf\", \"url\": \"https://bucketeer-5537c4b2-1591-443b-97e3-be39fb46da74.s3.amazonaws.com/formio-live/fake_file-9331c51c-70c8-4548-a3cd-ffb154ef5b35.pdf\", \"acl\": \"private\", \"size\": 13264, \"type\": \"application/pdf\", \"originalName\": \"fake_file.pdf\"}]",
    "",
    "2020-06-03T21:53:13.000Z",
    "https://ds-files.sfgov.org/formio-live/formio-live/fake_file-9331c51c-70c8-4548-a3cd-ffb154ef5b35.pdf"
]

JSON_OBJ = {
    "_id":"5f19eb423339194c18c45c7a",
    "data":{
        "actionState":"",
        "bluebeamStatus":"",
        "ptsStatus":"",
        "permitType":"existingBuilding",
        "reviewOverTheCounter":"yes",
        "onlyFireDepartmentReview":"yes",
        "applicantType":"contractor",
        "applicantFirstName":"",
        "applicantLastName":"",
        "applicantPhoneNumber":"",
        "applicantEmail":"",
        "applicantAddress":{
            "line1":"",
            "line2":"",
            "city":"San Francisco",
            "state":"california",
            "zip":"94124"
        },
        "applicantContractorLicenseNumber":"",
        "applicantContractorLicenseExpirationDate":"",
        "applicantBTRC":"",
        "applicantArchitectLicenseNumber":"",
        "applicantArchitectLicenseExpirationDate":"",
        "applicantEngineerLicenseNumber":"",
        "applicantEngineerLicenseExpirationDate":"",
        "buildingPermitApplicationNumber":"123456",
        "existingProjectAddress1":"existingProjectAddress1",
        "existingProjectAddress2":"existingProjectAddress2",
        "existingProjectZipCode":"",
        "existingProjectDescribeApplicationChanges":"",
        "ownerName":"",
        "ownerPhoneNumber":"",
        "ownerEmail":"",
        "ownerAddress":{
            "line1":"",
            "line2":"",
            "city":"SAN FRANCISCO",
            "state":"california",
            "zip":"94133"
        },
        "teamMembers":{
            "agent":"FALSE",
            "architect":"FALSE",
            "attorneyInFact":"FALSE",
            "contractor":"FALSE",
            "engineer":"FALSE"
        },
        "agentOrganizationName":"",
        "agentName":"",
        "agentEmail":"",
        "architectOrganizationName":"",
        "architectName":"",
        "architectEmail":"",
        "architectLicenseNumber":"",
        "architectLicenseExpirationDate":"",
        "attorneyOrganizationName":"",
        "attorneyName":"",
        "attorneyEmail":"",
        "contractorOrganizationName":"",
        "contractorName":"",
        "contractorEmail":"",
        "contractorLicenseNumber":"",
        "contractorLicenseExpirationDate":"",
        "contractorBTRC":"",
        "engineerOrganizationName":"",
        "engineerName":"",
        "engineerEmail":"",
        "engineerLicenseNumber":"",
        "engineerLicenseExpirationDate":"",
        "newBuildingLocation":"newBuildingLocation",
        "newBuildingBlockNumber":"",
        "newBuildingLotNumber":[
            ""
        ],
        "newBuildingLotFront":"",
        "newBuildingLotBack":"",
        "newBuildingLotAverageDepth":"",
        "newBuildingStreetFaced":"",
        "newBuildingStreetSide":"",
        "newBuildingNearestCrossStreet":"",
        "newBuildingCrossStreetDirection":"",
        "newBuildingCrossStreetDistance":"",
        "newBuildingLotHasOtherBuilding":"",
        "existingBuildingAddress1":"existingBuildingAddress1",
        "existingBuildingAddress2":"existingBuildingAddress2",
        "existingBuildingCity":"San Francisco",
        "existingBuildingState":"california",
        "existingBuildingZipCode":"94109",
        "existingBuildingBlockNumber":"0622",
        "existingBuildingLotNumber":[
            "003"
        ],
        "existingBuildingConstructionType":"vAProtectedWoodFrame",
        "existingBuildingDwellingUnits":"48",
        "existingBuildingOccupancyStories":"5",
        "existingBuildingBasementsAndCellars":"0",
        "existingBuildingPresentUse":{
            "singleFamilyHomeFamilyDwelling1":"FALSE",
            "duplexOr2UnitBuildingFamilyDwelling2":"FALSE",
            "apartments":"FALSE",
            "office":"FALSE",
            "other":"FALSE"
        },
        "existingBuildingPresentUseOther":[
            "a",
            "b"
        ],
        "existingBuildingOccupancyClass":[
            "r2ResidentialApartmentCondominiums",
            "mMercantile"
        ],
        "sitePermitForm38":"no",
        "noticeOfViolation":"no",
        "estimatedCostOfProject":"37000",
        "projectDescription":"DO STUFF",
        "typeOfConstruction":"vAProtectedWoodFrame",
        "proposedDwellingUnits":"48",
        "proposedOccupancyStories":"5",
        "proposedBasementsAndCellars":"0",
        "proposedUse":{
            "singleFamilyHomeFamilyDwelling1":"FALSE",
            "duplexOr2UnitBuildingFamilyDwelling2":"FALSE",
            "apartments":"FALSE",
            "office":"FALSE",
            "other":"FALSE"
        },
        "proposedUseOther":[
            "a",
            "b"
        ],
        "occupancyClass":[
            "r2ResidentialApartmentCondominiums",
            "mMercantile"
        ],
        "constructionLenderName":"",
        "constructionLenderBranchDesignation":"",
        "constructionLenderAddress1":"",
        "constructionLenderAddress2":"",
        "constructionLenderCity":"",
        "constructionLenderState":"",
        "constructionLenderZipCode":"",
        "sitePermitForm12":"",
        "newEstimatedCostOfProject":"",
        "newProjectDescription":"",
        "newTypeOfConstruction":"",
        "newBuildingUse":{
            "singleFamilyHomeFamilyDwelling1":"FALSE",
            "duplexOr2UnitBuildingFamilyDwelling2":"FALSE",
            "apartments":"FALSE",
            "office":"FALSE",
            "other":"FALSE"
        },
        "newBuildingUseOther":[
            "a",
            "b"
        ],
        "newOccupancyClass":"",
        "newGroundFloorArea":"",
        "newBuildingFrontHeight":"",
        "newDwellingUnits":"",
        "newOccupancyStories":"",
        "newBasements":"",
        "newConstructionLenderName":"",
        "newConstructionLenderBranchDesignation":"",
        "constructionLenderAddress3":"",
        "constructionLenderAddress4":"",
        "constructionLenderCity1":"",
        "constructionLenderState1":"",
        "constructionLenderZipCode1":"",
        "alterOrConstructDriveway":"no",
        "useStreetSpace":"no",
        "electricalWork":"no",
        "plumbingWork":"no",
        "additionalHeightOrStory":"no",
        "newCenterLineFrontHeight":"",
        "deckOrHorizontalExtension":"no",
        "groundFloorArea":"",
        "repairOrAlterSidewalk":"no",
        "extendBeyondPropertyLine":"no",
        "otherExistingBuildings":"no",
        "changeOfOccupancy":"no",
        "alterOrConstructDrivewayNew":"",
        "extendBeyondPropertyLineNew":"",
        "useStreetSpaceNew":"",
        "additionalStoriesNew":"",
        "howManyAdditionalStoriesNew":"",
        "useSidewalkSpaceNew":"",
        "affordableHousing":"no",
        "developmentAgreement":"no",
        "accessoryDwellingUnit":"no",
        "uploadType":"",
        "bluebeamId":"",
        "optionalUploads":[
            {
                "storage": "s3",
                "name": "A.pdf",
                "bucket": "bucket1",
                "key": "A.pdf",
                "url": "https://bucket1.amazonaws.com/A.pdf",
                "acl": "private",
                "size": 1,
                "type": "application/pdf",
                "originalName": "A.pdf"
            },
            {
                "storage": "s3",
                "name": "B.pdf",
                "bucket": "bucket1",
                "key": "B.pdf",
                "url": "https://bucket1.s3.amazonaws.com/B.pdf",
                "acl": "private",
                "size": 1,
                "type": "application/pdf",
                "originalName": "B.pdf"
            }
        ],
        "requiredUploads":[
            {
                "storage": "s3",
                "name": "C.pdf",
                "bucket": "bucket1",
                "key": "C.pdf",
                "url": "https://bucket1.amazonaws.com/C.pdf",
                "acl": "private",
                "size": 1,
                "type": "application/pdf",
                "originalName": "C.pdf"
            },
            {
                "storage": "s3",
                "name": "D.pdf",
                "bucket": "bucket1",
                "key": "D.pdf",
                "url": "https://bucket1.s3.amazonaws.com/D.pdf",
                "acl": "private",
                "size": 1,
                "type": "application/pdf",
                "originalName": "D.pdf"
            }
        ],
        "noPlansPermit":"FALSE",
        "notes":"",
        "workersCompRadio":"Have_workers_comp_insurance",
        "iHerebyCertifyCheckBox":"TRUE",
        "dateTime":"2020-07-23T19:49:37.000Z",
        "projectLocation2":"",
        "fileLinks":[
            "https://bucket1.amazonaws.com/A.pdf",
            "https://bucket1.s3.amazonaws.com/B.pdf",
            "https://bucket1.amazonaws.com/C.pdf",
            "https://bucket1.s3.amazonaws.com/D.pdf"
        ],
        "confirmationUploads":[],
        "priorityProjectSelections":{
            "isInDevelopmentAgreement":"TRUE",
            "is100AffordableHousing":"FALSE"
        },
        "projectAddress":"existingBuildingAddress1",
        "projectAddressNumber":"23",
        "projectAddressNumberSuffix":"",
        "projectAddressStreetName":"streetName",
        "projectAddressStreetType":"",
        "projectAddressUnitNumber":"",
        "projectAddressBlock":"21",
        "projectAddressLot":"100",
        "projectAddressZip":"11111",
        "applicantOrganizationName":"applicant org",
        "ownerOrganizationName":"owner org",
        "ownerFirstName":"owner first",
        "ownerLasttName":"owner last",
        "agentFirstName":"agent first",
        "agentLastName":"agent last",
        "agentPhoneNumber":"4151111111",
        "agentAddress":{
            "line1":"agent addr 1",
            "line2":"agent addr 2",
            "city":"agent city",
            "state":"agent state",
            "zip":"11111"
        },
        "architectFirstName":"architect first",
        "architectLastName":"architect last",
        "architectPhoneNumber":"4152222222",
        "architectAddress":{
            "line1":"architect addr 1",
            "line2":"architect addr 2",
            "city":"architect city",
            "state":"architect state",
            "zip":"11111"
        },
        "attorneyFirstName":"attorney first",
        "attorneyLastName":"attorney last",
        "attorneyPhoneNumber":"4153333333",
        "attorneyAddress":{
            "line1":"attorney addr 1",
            "line2":"attorney addr 2",
            "city":"attorney city",
            "state":"attorney state",
            "zip":"11111"
        },
        "contractorFirstName":"contractor first",
        "contractorLastName":"contractor last",
        "contractorPhoneNumber":"4154444444",
        "contractorAddress":{
            "line1":"contractor addr 1",
            "line2":"contractor addr 2",
            "city":"contractor city",
            "state":"contractor state",
            "zip":"11111"
        },
        "engineerFirstName":"eng first",
        "engineerLastName":"eng last",
        "engineerPhoneNumber":"4155555555",
        "engineerAddress":{
            "line1":"engineer addr 1",
            "line2":"engineer addr 2",
            "city":"engineer city",
            "state":"engineer state",
            "zip":"11111"
        },
    },
    "created":"2020-07-23T19:55:46.744Z",
    "modified":"2020-07-23T19:55:46.745Z"
}

JSON_OBJ_ADDENDA = {
    "_id": "5ed81beb463bc6df71e2500f",
    "data": {
        "actionState": "",
        "bluebeamStatus": "",
        "applicantType": "agent",
        "applicantFirstName": "Test",
        "applicantLastName": "Agent",
        "applicantPhoneNumber": "(415) 111-1111",
        "applicantEmail": "test@test.test",
        "applicantAddress1": "123 Test Street",
        "applicantAddress2": "",
        "applicantCity": "San Francisco",
        "Page2State": "california",
        "applicantZipCode": "94111",
        "applicantContractorLicenseNumber": "",
        "applicantContractorLicenseExpirationDate": "",
        "applicantBTRC": "",
        "applicantArchitectLicenseNumber": "",
        "applicantArchitectLicenseExpirationDate": "",
        "applicantEngineerLicenseNumber": "",
        "applicantEngineerLicenseExpirationDate": "",
        "sitePermitApplicationNumber": "12345678",
        "existingProjectAddress1": "123 Main Street",
        "existingProjectAddress2": "",
        "existingProjectZipCode": "94100",
        "affordableHousing": "yes",
        "developmentAgreement": "yes",
        "accessoryDwellingUnit": "yes",
        "addendaType": {
            "grading": "TRUE",
            "foundation": "TRUE",
            "shoringAndExcavation": "FALSE",
            "architectural": "FALSE",
            "superstructure": "FALSE",
            "title24EnergyMechanicalElectrical": "FALSE",
            "other": "FALSE"
        },
        "otherAddendaType": "",
        "addendaNumber": [12, 345, 678],
        "addendaCount": "2",
        "bluebeamId": "0",
        "requiredUploads": [
            {
                "storage": "s3",
                "name": "fake_file-9331c51c-70c8-4548-a3cd-ffb154ef5b35.pdf",
                "bucket": "bucketeer-5537c4b2-1591-443b-97e3-be39fb46da74",
                "key": "formio-live/fake_file-9331c51c-70c8-4548-a3cd-ffb154ef5b35.pdf",
                "url": "https://bucketeer-5537c4b2-1591-443b-97e3-be39fb46da74.s3.amazonaws.com/formio-live/fake_file-9331c51c-70c8-4548-a3cd-ffb154ef5b35.pdf",
                "acl": "private",
                "size": 13264,
                "type": "application/pdf",
                "originalName": "fake_file.pdf"
            }
        ],
        "applicationNotes": "",
        "dateTime": "2020-06-03T21:53:13.000Z",
        "fileLinks": "https://ds-files.sfgov.org/formio-live/formio-live/fake_file-9331c51c-70c8-4548-a3cd-ffb154ef5b35.pdf"
    },
    "created": "2020-06-03 02:53 PM PDT",
    "modified": "2020-06-03 02:53 PM PDT"
}

PATCH_RESPONSE = {
    "status": "success",
    "data": {
        "updates": [
            {
                "range": "B15",
                "values": [
                    [
                        "Queued for Bluebeam"
                    ]
                ]
            }
        ]
    }
}
